### ISSUE TITLE
[feature request] please support tab rearrangement

### ISSUE THREAD

**Issue by happyd0ggie** [linuxdeepin/deepin-terminal#14]
## OS version
Deepin 15.11 stable

## deepin-terminal version
3.2.7.1

## Problem
When opening multiple tabs, rearrangement of tabs is not supported.
When dragging the tab, the entire window will move instead of the tab.

**Comment by BLumia** [comment]
If you are using 15.11 I believe you are using [the GTK based deepin-terminal](https://github.com/linuxdeepin/deepin-terminal-old) instead of the new DTK one(this repo). Maybe we can add an issue template to avoid confusion? @xmuli

**Comment by XMuli** [comment]
Actually there is, otherwise mark it as Archive？ @BLumia 

![image](https://user-images.githubusercontent.com/33887845/87787412-2cb15b80-c86e-11ea-9c38-6a62da1ba5f5.png)

**Comment by BLumia** [comment]
> Actually there is, otherwise mark it as Archive?

No I means you can [create an issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) so user will see a default message when they create a new issue just like when they are using the [developer-center repo](https://github.com/linuxdeepin/developer-center/tree/master/.github/ISSUE_TEMPLATE) :)

Back to the topic. I'm not sure if the current DTK version will have tab rearrangement feature since the behavior is made by the designer and product manager. Anyway adding tab arrangement should be super easy but it still depends on the product manager and designer. I'm not a deepin employe so probably cannot help you more, sorry about that :/

And also FYI, for the old GTK based deepin-terminal, allowed drag and drop to reorder tab will make user hard to move the window by draging the titlebar area so we didn't introduce that feature.

**Comment by XMuli** [comment]
The current new terminal does not support drag and drop.
![image](https://user-images.githubusercontent.com/33887845/87846437-63d14c80-c902-11ea-948a-dbcd473f0959.png)

**Comment by XMuli** [comment]
> No I means you can [create an issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) so user will see a default message when they create a new issue just like when they are using the [developer-center repo](https://github.com/linuxdeepin/developer-center/tree/master/.github/ISSUE_TEMPLATE) :)

I'll put together a template when I have time.

**Comment by happyd0ggie** [comment]
Got. Thanks a lot.

**Comment by XMuli** [comment]
In the 2 warehouses of the terminal, the issuse template has been added
